### ISSUE TITLE
Image distorted on properties form

### ISSUE THREAD

**Issue by Brett-Parker** [dubstar-04/Design#114]
**Describe the bug**
Image distorted on property form when nothing selected.
 - Version [e.g. 43-aplha2] 

**Step to reproduce an issue (omit for feature request)**
Steps to reproduce the behaviour:
1. With nothing selected in the canvas, go to options
2. Click on properties
3. See distorted image

**Expected behaviour**
No distorted image. Not sure the image is adding anything.

**Supporting documents**
![image](https://user-images.githubusercontent.com/67550533/217544581-25076834-5f57-44aa-a5f8-387e415ca1ce.png)

**Comment by dubstar-04** [comment]
Screenshot is showing icon placeholder for missing icons. Can't reproduce the issue.
