### ISSUE TITLE
Unable to save empty drawing

### ISSUE THREAD

**Issue by Brett-Parker** [dubstar-04/Design#121]
**Describe the bug**
When saving a new document with nothing in the canvas, error is thrown
 - Version [e.g. 43-aplha2]

**Step to reproduce an issue **
Steps to reproduce the behaviour:
1. Open application new
2. Save drawing
3. See error in builder
4. Save dialog remains on screen for the user with no error message

**Expected behaviour**
Should be able to save drawing without anything in.

**Supporting documents**
![image](https://user-images.githubusercontent.com/67550533/217765186-579c45d3-0546-40ae-ade0-6ab943dcafa0.png)

**Comment by Brett-Parker** [comment]
#29 , #54 are related to this.

**Comment by dubstar-04** [comment]
Need to remove the check for an empty canvas too:

https://github.com/dubstar-04/Design/blob/main/src/Design/window.js#L180
