### ISSUE TITLE
Make documentation own repo/included in this one

### ISSUE THREAD

**Issue by Brett-Parker** [dubstar-04/Design#122]
**Describe the bug or feature**
Currently docs is stored in the [Design-Web](https://github.com/dubstar-04/Design-Web/tree/master/docs) repo. Either we need a dedicated docs section for this repo or make the Design-Web docs neutral and into a dedicated repo.

**Comment by dubstar-04** [comment]
https://github.com/dubstar-04/Design-Documentation
