### ISSUE TITLE
Middle mouse drag sticks

### ISSUE THREAD

**Issue by Brett-Parker** [dubstar-04/Design#124]
**Describe the bug or feature**
Middle mouse drag sticks 
 - Version [e.g. 43-aplha2] 

**Step to reproduce an issue (omit for feature request)**
Steps to reproduce the behaviour:
1. Open drawing
2. Middle mouse drag
3. Pan is stuck, user must click middle mouse again to release

**Expected behaviour**
Hold middle mouse to pan, once released, pan stops

**Supporting documents**
[Screencast from 09-02-23 15:20:27.webm](https://user-images.githubusercontent.com/67550533/217856910-8687de91-301c-423c-943f-a12ae9d94335.webm)

**Comment by dubstar-04** [comment]
This is related to bugs in GTK: 
https://gitlab.gnome.org/GNOME/gtk/-/issues/4939#note_1658418
https://gitlab.gnome.org/GNOME/gtk/-/issues/5573#note_1658412
