### ISSUE TITLE
Create of text does not allow spaces

### ISSUE THREAD

**Issue by Brett-Parker** [dubstar-04/Design#132]
**Describe the bug or feature**
When creating text, if space is pressed on text input, the text is created.
 - Version [e.g. 43-alpha3] 

**Step to reproduce an issue (omit for feature request)**
Steps to reproduce the behaviour:
1. Create text
2. Choose height
3. Start typing 'Test bug'
4. Note, text stopped at space

**Expected behaviour**
Should be able to create text with spaces

**Comment by dubstar-04** [comment]
Related to #118

**Comment by Brett-Parker** [comment]
PR submitted to core: https://github.com/dubstar-04/Design-Core/pull/62
