### ISSUE TITLE
Unable to open DXF (nothing seems to be displayed)

### ISSUE THREAD

**Issue by Peque** [dubstar-04/Design#140]
**Describe the bug**

When trying to open [this DXF file](https://drive.google.com/file/d/19o9hnaSCupBDQphN2hdyFg2oHEg7VOpi/view?usp=share_link) nothing seems to be displayed but no error message is shown either.

Note the file has a linked raster image for one layer. Visualizing this would definitely be a plus, but this issue aims to report only the "nothing is displayed" issue (the expected behavior would be to show the different layers with outlines/fills). :blush: 

 - Version 43-alpha3

**Comment by dubstar-04** [comment]
This is excellent. Thanks for taking the time to make a bug report.

**Comment by Peque** [comment]
Thanks to you for sharing your work! :blush:

**Comment by dubstar-04** [comment]
Found the issue: 

![image](https://user-images.githubusercontent.com/1136710/218402140-454bc251-2a6e-4cde-b11d-b3a0d337ae7a.png)

**Comment by dubstar-04** [comment]
@Peque The reported issue should now be fixed. Please continue to report any issues, helping to improve Design.

**Comment by Peque** [comment]
@dubstar-04 Awesome! :blush: 

Should I open an issue in this project for all layers being white and no fill color displayed? Or is it enough with https://github.com/dubstar-04/Design-Web/issues/155 ? (I'm guessing it is the same issue, but maybe not)

**Comment by dubstar-04** [comment]
I had a look at your file and all the colours are list as ACI 7
Where is the file being exported from?

There is a similar issue here for layers:
https://github.com/dubstar-04/Design/issues/139

The hatching and fill isn't currently supported. Please feel free to open a bug for that.

**Comment by Peque** [comment]
@dubstar-04 I opened this issue with more information: https://github.com/dubstar-04/Design/issues/145
