### ISSUE TITLE
Add support for Hatch fill

### ISSUE THREAD

**Issue by Peque** [dubstar-04/Design#146]
Opening [this DXF file](https://drive.google.com/file/d/19o9hnaSCupBDQphN2hdyFg2oHEg7VOpi/view?usp=share_link), the "Module fill" layer should represent the hatches filled this way:

![image](https://user-images.githubusercontent.com/526577/218501937-6f849790-2420-4aac-94de-3ac4d91751ef.png)

Ideally, gradients should be supported, although a solid fill could be a great starting point. :blush:

**Comment by dubstar-04** [comment]
fixed with #255

**Comment by Peque** [comment]
I can confirm it is working fine as a solid fill (without gradient) after latest Flatpak upgrade. :rocket: :blush:
