### ISSUE TITLE
Packages

### ISSUE THREAD

**Issue by Thatoo** [dubstar-04/Design#149]
Hello,

Could it be possible to install Design without the need of Flatpack using apt or .deb package system or the universal standalone .appimage package system?

**Comment by FabioLolix** [comment]
I'm working on a pkgbuild for AUR but it don't build at the moment

**Comment by dubstar-04** [comment]
Design will only be supporting Flatpak until a stable version is released. PRs may be considered for other package formats if someone is willing to maintain the packages.
