### ISSUE TITLE
Glowing effect on mouse over entities

### ISSUE THREAD

**Issue by jaisekjames** [dubstar-04/Design#220]
Add a Highlight effect on the entity as mouse hovered upon them.

![image](https://github.com/dubstar-04/Design/assets/44542605/35709ec3-24f0-433e-a1bc-14351faf724e)

**Comment by dubstar-04** [comment]
[Screencast from 2023-12-30 12-33-45.webm](https://github.com/dubstar-04/Design/assets/1136710/ace3cb40-a59a-4b1e-9979-73f9d44c6a83)

**Comment by dubstar-04** [comment]
fixed with #238

**Comment by jaisekjames** [comment]
waiting for testing latest update...
