### ISSUE TITLE
Cannot open any file

### ISSUE THREAD

**Issue by williamd1k0** [dubstar-04/Design#232]
I cannot open any file.

Version: 44-alpha4 and main

Steps to reproduce the behaviour:
Just try opening a file using Open Dialog or command-line argv.

## If using Open Dialog
The dialog itself simply doesn't appear.
After messing with the code, I managed to get it to work by setting the file filter after the dialog initialisation.

```diff
diff --git a/src/Design/fileIO.js b/src/Design/fileIO.js
index e3c7789..1964394 100644
--- a/src/Design/fileIO.js
+++ b/src/Design/fileIO.js
@@ -25,11 +25,11 @@ export class FileIO {
 
     const dialog = new Gtk.FileChooserNative({
       action: Gtk.FileChooserAction.OPEN,
-      filter: filter,
       select_multiple: false,
       transient_for: window,
       title: _('Open'),
     });
+    dialog.add_filter(filter);
 
     dialog.show();
     dialog.connect('response', (dialog, response) => {
```

## If using command-line argv
The app crashes before opening.
The log will warn you of this error:
```js
JS ERROR: TypeError: activeWindow.load_file is not a function
DesignApplication/</<@resource:///io/github/dubstar_04/design/js/Design/main.js:73:26
```
I haven't found a way to fix it myself though.

**Comment by dubstar-04** [comment]
Thanks for the report. This works for me on Debian and Fedora. File opening is done through the flatpak portal. 
What OS are you using?

**Comment by williamd1k0** [comment]
I'm using Manjaro 23.0.2 Xfce4.

**Comment by dubstar-04** [comment]
@williamd1k0 please can you provide examples of the files that won't open?

**Comment by dubstar-04** [comment]
How are you launching the application?

**Comment by dubstar-04** [comment]
No response. Closing issue.
