### ISSUE TITLE
Latest git checkout fails to build

### ISSUE THREAD

**Issue by prokoudine** [dubstar-04/Design#248]
The latest code (commit 75511204) fails to build on Ubuntu 23.10:

```
[1/8] Generating src/io.github.dubstar_04.design.src_gresource with a custom command
FAILED: src/io.github.dubstar_04.design.src.gresource 
/usr/bin/glib-compile-resources ../src/io.github.dubstar_04.design.src.gresource.xml --sourcedir ../src --internal --generate --target src/io.github.dubstar_04.design.src.gresource --dependency-file src/io.github.dubstar_04.design.src.gresource.d
../src/io.github.dubstar_04.design.src.gresource.xml: Failed to locate “Design-Core/core/designCore.js” in any source directory.
[6/8] Generating data/blueprints with a custom command
ninja: build stopped: subcommand failed.
```

Any additional info I can provide you?

**Comment by dubstar-04** [comment]
The error suggests that design-core submodule isn't updating. You could try a fresh clone or git pull --recurse-submodules

**Comment by dubstar-04** [comment]
If this is a fresh clone you will need to check if the Design-core directory has any contents. If you may need to clone with submodules: git clone --recurse-submodules

**Comment by prokoudine** [comment]
Silly me, sorry about the noise.

**Comment by dubstar-04** [comment]
No worries. It's nice to know that someone is interested enough to be playing and testing.
