### ISSUE TITLE
App icon following the GNOME style

### ISSUE THREAD

**Issue by bragefuglseth** [dubstar-04/Design#52]
Hi! GNOME has a set of [guidelines](https://developer.gnome.org/hig/guidelines/app-icons.html) for app icons. Design's current icon looks out-of-place among other GNOME apps, so I wonder if it's within the scope of this app to have an icon following the GNOME style?

I can probably try to design one if you want me to. You can also check out [#appicondesign:gnome.org](https://matrix.to/#/%23appicondesign:gnome.org) to ask for help. 😁

**Comment by dubstar-04** [comment]
I would absolutely love some help with the icon. Although I am very fond of the protractor and would be sad to see it go :(
