### ISSUE TITLE
Crossing Selection Window on Arcs.

### ISSUE THREAD

**Issue by DangerM0ose** [dubstar-04/Design#82]
Using the crossing selection window on a section of an arc does not add it to the selection set. Circles seem to work fine but as soon as you trim the circle to form an arc it beaks.

**Comment by dubstar-04** [comment]
I can't seem to replicate this issue. Do you have a DXF where this happens that you can share?

[Screencast from 2023-02-06 12-41-33.webm](https://user-images.githubusercontent.com/1136710/216974304-c031cd23-01c9-47fb-b158-ecac88b409f6.webm)
